services:
  redis:
    image: redis:7-alpine
    container_name: simplifica-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgres:
    image: postgres:16-alpine
    container_name: simplifica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-simplifica}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-simplifica123}
      POSTGRES_DB: ${DB_NAME:-simplifica}
    ports:
      - '${DB_PORT_EXTERNAL:-5433}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-simplifica}']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
    container_name: simplifica-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER:-simplifica}:${DB_PASSWORD:-simplifica123}@postgres:5432/${DB_NAME:-simplifica}?schema=public
      API_URL: ${API_URL:-http://localhost:3000/api}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-troque_este_segredo_em_producao}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      SEED_ON_START: ${SEED_ON_START:-false}
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  pgdata:
